base: &base
  incudia:
    host: localhost
    https: false
    protocol: https
    port: 3000
    allow_username_or_email_login: true
    logfile: <%= "#{Rails.env}.#{`hostname`.chomp}.log" %>
    extra:
      # Allow non-admin users to create projects
      allow_user_project_creation: false
      ## Google analytics. Uncomment if you want it
      # google_analytics_id: '_your_tracking_id'

  ## OmniAuth settings
  omniauth:
    # Allow login via Twitter, Google, etc. using OmniAuth providers
    enabled: true

    # CAUTION!
    # This allows users to login without having a user account first (default: false).
    # User accounts will be created automatically when authentication was successful.
    allow_single_sign_on: true
    # Locks down those users until they have been cleared by the admin (default: true).
    block_auto_created_users: false

    ## Auth providers
    # Uncomment the following lines and fill in the data of the auth provider you want to use
    # If your favorite auth provider is not listed you can use others:
    # see https://github.com/gitlabhq/gitlabhq/wiki/Using-Custom-Omniauth-Providers
    # The 'app_id' and 'app_secret' parameters are always passed as the first two
    # arguments, followed by optional 'args' which can be either a hash or an array.
    providers:
      # - { name: 'google_oauth2', app_id: 'YOUR APP ID',
      #     app_secret: 'YOUR APP SECRET',
      #     args: { access_type: 'offline', approval_prompt: '' } }
      # - { name: 'twitter', app_id: 'YOUR APP ID',
      #     app_secret: 'YOUR APP SECRET'}



production:
  <<: *base

development:
  <<: *base

test:
  <<: *base
  issues_tracker:
    redmine:
      project_url: "http://redmine/projects/:issues_tracker_id"
      issues_url: "http://redmine/:project_id/:issues_tracker_id/:id"
      new_issue_url: "http://redmine/projects/:issues_tracker_id/issues/new"
